# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 20:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='labeller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labeller', to='app.MyUser'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='app.MyUser'),
        ),
    ]
